# Generated by Django 2.2.6 on 2020-01-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.TextField(help_text='Название раздела')),
                ('page_link', models.TextField(help_text='Ссылка на раздел')),
            ],
        ),
    ]
