# Generated by Django 3.0.2 on 2020-06-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FromForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_text', models.CharField(help_text='То что мы берём из формы - попадает сюда', max_length=300)),
            ],
        ),
    ]
