# Generated by Django 2.2.6 on 2020-01-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Никнейм', max_length=12, unique='true')),
                ('realname', models.CharField(help_text='Имя', max_length=24)),
                ('status', models.TextField(help_text='Статус пользователя', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=300)),
                ('id_user', models.ForeignKey(on_delete='CASCADE', to='second.User')),
            ],
        ),
    ]
