# Generated by Django 3.0.2 on 2020-06-28 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('D', '0003_auto_20200626_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='id_header',
        ),
        migrations.AddField(
            model_name='article',
            name='id_header',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='D.Header', verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='article',
            name='id_images',
        ),
        migrations.AddField(
            model_name='article',
            name='id_images',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='D.Image', verbose_name='Картинки'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='article',
            name='id_paragraph',
        ),
        migrations.AddField(
            model_name='article',
            name='id_paragraph',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='D.Paragraph', verbose_name='Параграфы'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='article',
            name='id_quote',
        ),
        migrations.AddField(
            model_name='article',
            name='id_quote',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='D.Quote', verbose_name='Цитаты'),
            preserve_default=False,
        ),
    ]
