# Generated by Django 3.0.2 on 2020-06-28 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('D', '0004_auto_20200629_0025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='image',
            new_name='prewiew_image',
        ),
        migrations.RemoveField(
            model_name='article',
            name='id_header',
        ),
        migrations.RemoveField(
            model_name='article',
            name='id_images',
        ),
        migrations.RemoveField(
            model_name='article',
            name='id_paragraph',
        ),
        migrations.RemoveField(
            model_name='article',
            name='id_quote',
        ),
        migrations.AddField(
            model_name='header',
            name='id_article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='D.Article', verbose_name='Статья'),
        ),
        migrations.AddField(
            model_name='image',
            name='id_article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='D.Article', verbose_name='Статья'),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='id_article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='D.Article', verbose_name='Статья'),
        ),
        migrations.AddField(
            model_name='quote',
            name='id_article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='D.Article', verbose_name='Статья'),
        ),
    ]
