# Generated by Django 3.0.2 on 2020-06-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('D', '0005_auto_20200629_0037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='prewiew_image',
            new_name='preview_image',
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Заголовок'),
        ),
    ]
