# Generated by Django 3.0.2 on 2020-06-29 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('D', '0006_auto_20200629_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(help_text='Картинка', upload_to='images/article_img'),
        ),
    ]
